name: Auto Run make test

on:
    push:
        branches:
            - main
    pull_requests:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            
            - name: Set up Python
              uses: actions/setup_python@v3
              with:
                python-version: '3.x'

            - name: Setup requirements
              run: |
                 make setup

            - name: Run make test
              run: |
                 make test
            
